# Generated by Django 4.2.1 on 2023-05-17 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_profile_duration_energy_companytime'),
        ('EnergyCapture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleDeviceID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnergyCapture.station'),
        ),
        migrations.AddField(
            model_name='powerclamp',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnergyCapture.equipment'),
        ),
        migrations.AddField(
            model_name='station',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.company'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerclamp',
            name='deviceID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='powerclamp',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StationTime',
            fields=[
                ('power', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnergyCapture.station')),
            ],
        ),
        migrations.CreateModel(
            name='PowerClampTime',
            fields=[
                ('power', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('powerClamp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnergyCapture.powerclamp')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentTime',
            fields=[
                ('power', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EnergyCapture.equipment')),
            ],
        ),
    ]
