# Generated by Django 4.2.1 on 2023-05-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnergyCapture', '0004_alter_equipment_total_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='total_power',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='powerclamp',
            name='total_power',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='total_power',
            field=models.FloatField(default=0, null=True),
        ),
    ]
