# Generated by Django 4.2.1 on 2023-05-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_company_co2_choice'),
        ('EnergyCapture', '0005_alter_equipment_total_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Scope 2', 'Scope 2'), ('Scope 3 (Generation)', 'Scope 3 (Generation)'), ('Scope 3 (Transmission and Distribution', 'Scope 3 (Transmission and Distribution'), ('Total', 'Total')], max_length=50, null=True)),
                ('value', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.company')),
            ],
        ),
    ]
