# Generated by Django 4.2.1 on 2023-05-17 12:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='duration_energy',
            field=models.DecimalField(decimal_places=3, default=0.06, max_digits=30, null=True),
        ),
        migrations.CreateModel(
            name='CompanyTime',
            fields=[
                ('power', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.company')),
            ],
        ),
    ]
