# Generated by Django 4.2.1 on 2023-05-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_profile_duration_energy_companytime'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_power',
            field=models.DecimalField(decimal_places=3, max_digits=50, null=True),
        ),
    ]
