# Generated by Django 4.2.1 on 2023-05-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_company_total_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='total_power',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=50, null=True),
        ),
    ]
